### PR TITLE
Amended "coures" to "course".

### PR DESCRIPTION
**Pull request by tangerine**

### CODE REVIEW

**Comment by isaiahdw** [comment]
Arg! Silly me playing around with the new merge button. This should **not** be merged into master.

You need to open an issue for this on our issue tracker [here](http://dev.kohanaframework.org/projects/kohana3/issues).

**Comment by tangerine** [comment]
Er...why?  Is this always the case for spelling corrections?

**Comment by parshap** [comment]
Any change to the codebase (documentation included, apparently) must have an issue created in Kohana's [issue tracker](http://dev.kohanaframework.org/projects/kohana3) to represent it.

**Comment by slacker** [comment]
Also it was merged into master and not the development branch.  Only releases go into the master branch. See https://github.com/kohana/kohana/wiki/developers .

**Comment by isaiahdw** [comment]
Sorry about the confusion. Merging into the master was my mistake, not yours. It's fine to submit pull requests on the master branch, we (the devs) just need to make sure they get merged into the correct branch(es). However we do need issues created for everything no matter how simple or small the change is. Every commit needs to reference an issue number.

**Pull request merged**
