### PR TITLE
Fixed bug #4240

### PR DESCRIPTION
**Pull request by AlexC**
This also effects 3.3/develop and will need merging into that branch too

### CODE REVIEW

**Comment by zeelot** [comment]
Could you write some tests for this? Seems like we have `URL::query()` tests already so adding a recursive array to `provider_query()` should do the trick.

**Comment by stillman** [comment]
The patch is incorrect!

``` php
<?php
$_GET['a'] = 'a';
echo urldecode(URL::query(array('a' => 'b'))); // Produces ?a[0]=a&a[1]=b instead of ?a=b
```

**Comment by zeelot** [comment]
I guess it should use `Arr::merge()` instead? Anyway, that's why we should write some tests ;)

**Comment by AlexC** [comment]
@stillman Shouldn't your example return '?a=b' instead?

I've just forced-pushed to my branch which changes to Arr::merge() and adds some unit test data.

**Comment by stillman** [comment]
@AlexC Yes, sure! Thanks

**Comment by zeelot** [comment]
Perfect, many thanks! :)

**Pull request merged**
