### PR TITLE
3.3/feature/3989 remove cli

### PR DESCRIPTION
**Pull request by zombor**
This is the pull request discussion for specific code changes for removing cli from kohana-core. Please keep idea discussions on redmine.

### CODE REVIEW

**Comment by kiall** [comment]
Looks like an extra CLI test case still hanging around?

**Comment by kiall** [comment]
Looks good to me, merge away if you're happy with it :)

**Comment by shadowhand** [comment]
What are we replacing this with?

**Comment by kiall** [comment]
The CLI stuff is being cleared out to help with simplifying the request/response class and isolating HTTP from CLI...

Minion is coming in as a generic CLI task runner to replace it, You could consider it a little like Ruby's Rake..

**Comment by zombor** [comment]
http://dev.kohanaframework.org/issues/3989

**Pull request merged**
