### PR TITLE
Change detecting urls starting with //

### PR DESCRIPTION
**Pull request by arkagod**
Change detecting urls starting with // in Form::open, HTML::script, HTML::style and HTML::image + support data-scheme in HTML::image

### CODE REVIEW

**Comment by enov** [comment]
Sorry for the late reply @arkagod.

I think this is good and can go to `3.3/develop`.

Regarding `array()` => `[]` changes, you need to do that in separate PR, targeting `3.4/develop`.

cc @acoulton @rjd22

**Comment by rjd22** [comment]
@enov I think we can merge this. It doesn't have to be in 3.3 :)

**Comment by enov** [comment]
Yeah, it doesn't have to be in 3.3... merging!

Thanks @arkagod, @rjd22.

**Comment by WinterSilence** [comment]
it's not all (=  https://github.com/kohana/core/blob/3.4/develop/classes/Kohana/Request.php#L682
`if ( ! $allow_external OR strpos($uri, '://') === FALSE)`, need run search in files for finds all strings with `://`

**Pull request merged**
