### PR TITLE
Fixes #4147, Translated messages should not rely on the default language being English

### PR DESCRIPTION
**Pull request by ernestas**

### CODE REVIEW

**Comment by shadowhand** [comment]
What if two different languages have the same word or phrase but mean different things? For instance, if English has "No" meaning "No", and another language has "No" meaning "Two". In this situation, it is impossible to translate both correctly, as they are saying the same space.

TL;DR: To implement this change, the format of I18n files would have to be changed dramatically.

**Comment by shadowhand** [comment]
One solution would be (`i18n/en.php`):

``` php
<?php defined('SYSPATH') or die('No direct script access.');

return array(
    'es' => array(
        'Español' => 'Spanish',
        '¡Hola, mundo!' => 'Hello, world!',
    ),
    'fr' => array(
        'Français' => 'French',
        'Bonjour, monde!' => 'Hello, world!',
    ),
);
```

Any thoughts on this format?

**Comment by shadowhand** [comment]
Related: #199.

**Comment by ernestas** [comment]
Reverted #4120 since it brings more complexity than the intent of the change. Will use gettext or https://github.com/czukowski/I18n_Plural

**Comment by zeelot** [comment]
Closing since you seem to have gone with other options

**Pull request closed without merging**
