### PR TITLE
Merge 3.2/master into 3.3/develop

### PR DESCRIPTION
**Pull request by enov**
Merge conflicts resolution:

The following files had merge conflicts.

These files were kept as they were in 3.3/develop:
- classes/Kohana/Arr.php
- classes/Kohana/Config/Group.php
- classes/Kohana/Config/Source.php
- classes/Kohana/Config/Writer.php
- classes/Kohana/Debug.php
- classes/Kohana/HTTP.php
- classes/Kohana/HTTP/Header.php
- classes/Kohana/HTTP/Message.php
- classes/Kohana/HTTP/Request.php
- classes/Kohana/HTTP/Response.php
- classes/Kohana/Log/StdErr.php
- classes/Kohana/Log/StdOut.php
- classes/Kohana/Response.php
- classes/Kohana/UTF8.php
- guide/kohana/index.md
- guide/kohana/mvc/controllers.md
- guide/kohana/routing.md
- guide/kohana/upgrading.md
- system/utf8/ucwords.php
- classes/Kohana/Core.php
- tests/kohana/ArrTest.php
- tests/kohana/Config/File/ReaderTest.php
- tests/kohana/Config/GroupTest.php
- tests/kohana/CoreTest.php
- tests/kohana/DebugTest.php
- tests/kohana/Http/HeaderTest.php

These files have some changes merged:
- classes/Kohana/UTF8.php (mb_substitute_character set/reset)
- classes/Kohana/Request.php (merged changes from 3.2.3)
- classes/Kohana/Route.php (merged changes from 3.2.3)
- classes/Kohana/Text.php (merged widont function from 3.2.3)
- tests/kohana/RequestTest.php (merged tweaked changes from 3.2.3)
- tests/kohana/RouteTest.php (merged changes from 3.2.3)

### CODE REVIEW

**Comment by enov** [comment]
That's interesting... Travis first [passed](https://travis-ci.org/kohana/core/builds/36329666), now it's failing.

**Comment by acoulton** [comment]
@enov the failing test was #559 - I've seen that a couple of times last week but hadn't had a chance to look into it yet. When I restarted the build it's green.

**Comment by acoulton** [comment]
@enov great work, thanks!

**Comment by acoulton** [comment]
@enov @Ikke who should be responsible for deleting pull request branches in the core repos once they're merged? The person merging or the person submitting?

**Comment by enov** [comment]
Sorry for being messy!

:blush: I guess the person submitting should know how to clean up after himself :blush:

**Comment by acoulton** [comment]
@enov you're not the only one :grinning: - obviously it's very easy for the merger to delete, but maybe safest to leave it for the submitter just in case?

**Comment by enov** [comment]
> obviously it's very easy for the merger to delete, but maybe safest to leave it for the submitter just in case?

I guess so :)

**Pull request merged**
