### PR TITLE
Fixed links to tutorial for template driven site

### PR DESCRIPTION
**Pull request by yakatz**
Might want to include the content instead and credit that site, just in case it changes again.

### CODE REVIEW

**Comment by zombor** [comment]
We should just remove all external "tutorials" to other sites in the docs. For example, this one is is just out of date, and won't work in 3.3. There's other links that are broken as well.

Also, this PR would need to target 3.3/develop, not master.

**Comment by zombor** [comment]
You should also make a ticket in redmine for any issues you file.

**Comment by yakatz** [comment]
I just used the editor built into Github because it was a small and quick change. I am looking at how long it would take to create an updated doc for templates and I might just do it.

**Comment by zombor** [comment]
K, just make sure you read the development guidelines:

https://github.com/kohana/kohana/wiki/Kohana-Development-Procedures
https://github.com/kohana/kohana/wiki/developers

**Pull request closed without merging**
