### PR TITLE
fixing broken links on the main guide page

### PR DESCRIPTION
**Pull request by mintbridge**
i've fixed the links, though some of them, namely signed cookies and database security are pretty redundant, so maybe they need removing all together?

### CODE REVIEW

**Comment by shadowhand** [comment]
Can this be targeted to 3.1?

**Comment by mintbridge** [comment]
probably they're broken from 3.0 onwards as far as I can tell, ill check against 3.1 now..

**Comment by mintbridge** [comment]
Yes they can go against 3.1, would you like a new pull request?

**Comment by shadowhand** [comment]
Yes, please create a new pull request and target it at `3.1/develop`. Thanks!

**Comment by mintbridge** [comment]
new pull at https://github.com/kohana/core/pull/201

**Pull request closed without merging**
