### PR TITLE
Fixed bug with incorrect mime type

### PR DESCRIPTION
**Pull request by stillman**
Issue [#4344](http://dev.kohanaframework.org/issues/4344).

### CODE REVIEW

**Comment by shadowhand** [comment]
Why would using `$filename` in this context cause an issue?

**Comment by stillman** [comment]
Because file name that will be show in the download/open file dialog is in the $download variable and it seems logical to get mime type for it. Original file may not have extension at all (especially when download is generated from the current response [Use TRUE for the filename to send the current response as the file content])

**Comment by cs278** [comment]
If `$filename` is true it uses `$download` for the MIME type.

**Comment by stillman** [comment]
Okay, I want to give the user file named "picture.jpg", but the original file stored as md5_file($file) (without extension). What mime type should be in this case?

**Comment by shadowhand** [comment]
Ah, I see... the sent filename should match the sent mime-type.

Please [create an issue](http://dev.kohanaframework.org/projects/kohana3/issues) and reference the pull request so that this doesn't get lost. Editing the pull request to also edit the ticket gets bonus points.

Thanks!

**Comment by stillman** [comment]
Already did :)
http://dev.kohanaframework.org/issues/4344

**Pull request merged**
