### PR TITLE
Update classes/kohana/arr.php

### PR DESCRIPTION
**Pull request by misterx**

### CODE REVIEW

**Comment by rjd22** [comment]
You are missing the following things before your pull request will be accepted:
- Tests
- ticket number
- better commit description
- and push to 3.3/develop

Thank you :)

**Comment by misterx** [comment]
Sorry, this is my first push )

**Comment by misterx** [comment]
Show me rules plz, where i can read about test, ticket number (this don't have ticket) ?)

**Comment by loonies** [comment]
https://github.com/kohana/kohana/wiki

**Comment by zeelot** [comment]
What's the reason for this change? Could you file a ticket on redmine with an explanation? Once it's been created you can make a pull request to 3.2/develop (we don't merge pull requests to any master branch).

Thanks

**Pull request closed without merging**
