### PR TITLE
Fixes #4813 by Using Kohana_UTF8 from version 3.3 to apply all the patches

### PR DESCRIPTION
**Pull request by enov**
Fixes Kohana_UTF8Test::test_clean with data set no.3
and Kohana_DebugTest::test_dump with data set no.6

### CODE REVIEW

**Comment by zeelot** [comment]
Can you add a failing test for this?

**Comment by enov** [comment]
@Zeelot, The mentioned test were already failing in PHP5.4 and 5.5.

**Comment by zombor** [comment]
We should probably add 5.4 and 5.5 to our travisCI configuration. We don't officially support these versions right now though.

**Comment by enov** [comment]
@zombor , I have setup travis on my fork:
https://travis-ci.org/enov/kohana
It includes this PR, and it's all green for PHP 5.3 and 5.4.
PHP 5.5 still requires preg_replace with /e modifier fix.

So, could we have this merged?

**Comment by zeelot** [comment]
Thanks! How do we update travis to run on the newer PHP versions?

**Comment by enov** [comment]
just add 5.4 and 5.5 to .travis.yml, like this:
https://github.com/enov/kohana/blob/3.2/develop/.travis.yml#L6

**Pull request merged**
