### PR TITLE
3.1/fix 4012

### PR DESCRIPTION
**Pull request by Ikke**
Fixes [#4012](http://dev.kohanaframework.org/issues/4012)

### CODE REVIEW

**Comment by Ikke** [comment]
I fixed the unittests and added some new unittests to handle for all situations.

`arr::get()` should now return the value even if the value == NULL and still work for ArrayAccess objects.

Fixes #4012

**Comment by kiall** [comment]
Apologies, Just restored CI server from backup .. Its not quite fixed yet ;) Ignore those last messages!

!build

**Comment by kiall** [comment]
@Ikke Looks good to me, Considering this changes the behaviour of how NULL values are treated, I think this needs to go into the 3.3/develop branch.

Also - There are a few Coding Style issues:

1) Indentation inside the test provider seems wrong, probably the wrong combination of spaces and tabs..
2) the if / else block needs {'s per the CS guide

Thanks :)

**Comment by shadowhand** [comment]
I don't see a reason to change the current behavior of 3.1, as it is nearing its EOL.

**Comment by Ikke** [comment]
There is a new pull request for 3.3

On Thu, Jan 5, 2012 at 7:25 AM, Woody Gilk
reply@reply.github.com
wrote:

**Pull request closed without merging**
