### PR TITLE
Update HTML.php

### PR DESCRIPTION
**Pull request by fabiotnt**
To support less files

### CODE REVIEW

**Comment by sergeyklay** [comment]
The [HTML5 spec](http://dev.w3.org/html5/spec/Overview.html#the-link-element) says that the type attribute is purely advisory and explains in detail how browsers should act if it's omitted.

It seems `$attributes['type']` should be removed. If the user really needs it - it could specify it explicitly

**Comment by shadowhand** [comment]
@sergeyklay agree, we should be transitioning towards HTML5, but as it stands, we still target XHTML, which says that `type` is recommended for stylesheets.

**Comment by enov** [comment]
@fabiotnt could you kindly point this towards 3.3/develop? Thanks!

**Comment by enov** [comment]
BTW, I also noticed that the `type` attribute is recommended to be `text/css` similar to the standard CSS `link` tag. See [lesscss.org](http://lesscss.org):

> `<link rel="stylesheet/less" type="text/css" href="styles.less" />`

So @shadowhand, would you kindly let me know if we still need to have this?

**Pull request closed without merging**
