### PR TITLE
PHP7 support

### PR DESCRIPTION
**Pull request by enov**

### CODE REVIEW

**Comment by neo22s** [comment]
hello! any news on this? how can I help? what is uncompatible?

so far only found an issue on the pagination module, working on it.

**Comment by neo22s** [comment]
Seems also theres an issue with the kohana/kohana/exception.php

response(Exception $e) doesnt work but response($e) it does.

**Comment by enov** [comment]
@neo22s this PR is already merged and only adds PHP 7.0 to Travis CI build matrix.

If Kohana has a problem running on PHP 7.0, kindly open a new issue. Also, kindly provide enough details to reproduce the issue.

Thanks :)

**Comment by neo22s** [comment]
Sure! Should I open it in the core? no problem, as far as I have tested works great all except this 2 minor issues ;)

**Comment by neo22s** [comment]
https://github.com/kohana/core/issues/642

**Pull request merged**
