### PR TITLE
PSR-0 fix class name

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by zeelot** [comment]
Fixed in `3.3/develop` already, thanks.

**Comment by WinterSilence** [comment]
i don`t see this:
https://github.com/kohana/core/blob/3.3/develop/classes/Kohana/I18n.php

https://github.com/kohana/core/blob/3.4/develop/classes/Kohana/I18n.php

**Comment by zeelot** [comment]
The change in this PR shows this https://github.com/kohana/core/blob/3.3/develop/classes/Kohana/View.php#L238-L240

**Comment by WinterSilence** [comment]
@Zeelot, sorry, misunderstood, i thought it about http://dev.kohanaframework.org/issues/4780

**Pull request closed without merging**
