### PR TITLE
Fixed typo in comments for Kohana_View::__toString()

### PR DESCRIPTION
**Pull request by robbytaylor**
I haven't opened a ticket since it's such a small comment change...

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
Is this actually a typo?

> We use this method here because it's impossible to throw an exception from __toString().

This sounds right to me.

**Comment by zombor** [comment]
`and` vs `an`

**Comment by zombor** [comment]
Should this target 3.3/develop? Is the typo there as well?

**Comment by robbytaylor** [comment]
I noticed it while looking through the View class in 3.3/master, so yeah, you're right, it should target 3.3/develop.

**Pull request closed without merging**
