### PR TITLE
Synapse bugfix/3215 inflector count params

### PR DESCRIPTION
**Pull request by zeelot**
fixes http://dev.kohanaframework.org/issues/3215 and tests pull requests 2.0 =P

### CODE REVIEW

**Comment by kiall** [comment]
Merged

**Comment by shadowhand** [comment]
This does more than just change to floats, the logic/flow changes need to be removed.

**Comment by zeelot** [comment]
I thought I simplified it a bit, the reason I moved the 'remove garbage' section down was because the one above it says 'do nothing' so it would have been inaccurate

**Comment by shadowhand** [comment]
I guess it should say "do nothing else" then.  ;) Logic should follow through. Test: `Hamster => hamsters` and you'll see.

**Comment by zeelot** [comment]
well actually, why are we running strtolower on it? how is that part of the process involved in pluralizing a string?

**Comment by shadowhand** [comment]
Pretty hard to use array features when you don't normalize what you are searching for.

**Comment by shadowhand** [comment]
Uh, kiall, I explicitly said that this needs to be fixed before it can be merged. Please revert your merge.

**Pull request closed without merging**
