### PR TITLE
Doc: Updates for the coding guideline

### PR DESCRIPTION
**Pull request by goyote**
http://dev.kohanaframework.org/issues/3816

### CODE REVIEW

**Comment by shadowhand** [comment]
Actually `class Foo {  }` is the correct option; 2 spaces inside empty brackets.

**Comment by goyote** [comment]
Can we change that?

1) Empty brackets are currently being used everywhere in the source code, e.g `class Arr extends Kohana_Arr {}` (with the exception of a couple of places.)

2) Empty brakets are more intuitive, since we already remove whitespace from similar structures, e.g. 
`$arr[] = $item;`, `$empty = array();`

**Comment by shadowhand** [comment]
It used to be that empty curlies would have two spaces between them, but I am fine with being more consistent.

**Comment by goyote** [comment]
yay :)

**Comment by shadowhand** [comment]
b705e0b7b7f1836c6bcd3b464adedcc1f8ccb942

**Pull request closed without merging**
