### PR TITLE
3.0.x

### PR DESCRIPTION
**Pull request by ellisio**
Modified documentation for core to better support IDEs with support for auto-complete.

### CODE REVIEW

**Comment by ellisio** [comment]
I viewed the ticket on Redmine, and there isn't an option for me to associate a revision to the ticket #. Can you please do this for me?

Regards,
Andrew

**Comment by ThePixelDeveloper** [comment]
Just add a comment with a link to this pull request, that's all they're asking for.

**Comment by ellisio** [comment]
Done and done. :)

**Comment by rafi** [comment]
Oh man, this is great! thanks for doing it

**Comment by pocesar** [comment]
awesome, I was about to do the same lol

**Comment by seeYouInHell** [comment]
@access property is useless for PHP5.

**Comment by ellisio** [comment]
Out curiosity why is that useless when it's meant purely for documentation purposes?

**Comment by seeYouInHell** [comment]
This property was introduced because of PHP4 hasn't public, protected and private keywords. Now we can see visibility modifier without @access property. So this property is inconsistent with PHP5 code.

**Comment by ellisio** [comment]
Do PHPDOC generators read the code's access key though? If not, I would assume @access is still useful for doc generation?

**Comment by pocesar** [comment]
yes, it's still useful for documentation (aside from the code completion on IDEs)

**Comment by shadowhand** [comment]
Please remove `@access`, it is completely useless in PHP5 code.

**Comment by shadowhand** [comment]
And please follow our conventions for `@var` comments:

```
@var  type  comment
```

I see several places where you are using:

```
comment
@var  type
```

Which does not fit our coding style.

**Comment by mikelbring** [comment]
`@access` is not pointless. As mentioned before its for PHPDOC and IDEs.

**Comment by ellisio** [comment]
I'll revise the comments, but I disagree about the `@access` key. This is purely documentation, and that key is used in PHPDoc generators to document what kind of access the method has as they can not read the actual access keys on the code.

But if those need to be removed for this change to go in, I'll make that change, but I completely disagree with this.

**Comment by shadowhand** [comment]
It doesn't matter if you disagree, phpdoc only defines `@access` before of PHP4. If your IDE is too stupid to understand the PHP, too bad.

**Comment by ellisio** [comment]
This is a community driven framework, there is no reason you should be taking feedback from the community and rebuttal with attitude. If you don't want community feedback on general day-to-day user needs, then make this a closed-source framework and charge for it.

Anyways, I'm making the changes now, I'll close this and send another pull request shortly.

**Comment by shadowhand** [comment]
We will still accept your patch, we just don't want to encourage the use of legacy features.

**Comment by shadowhand** [comment]
Merged in c7432cdaeccd47b58d55bb61e89c281738bc8096

**Pull request merged**
