### PR TITLE
Fixed bug #4208

### PR DESCRIPTION
**Pull request by AlexC**
This also effects 3.3/develop

### CODE REVIEW

**Comment by GeertDD** [comment]
This change introduces a new bug as demonstrated below.

```
Text::auto_link_urls('www.example.be'); // Fails
Text::auto_link_urls('www.example.com'); // Succeeds
```

The problem is that in this part of the regex `\.[a-z]{2,6}[^<\s]+`, you are _requiring_ a character to follow the top-level domain extension. In the examples above, no characters follow after it, so the regex has to backtrack. The backtracking works only as long as the top-level domain extension consist of at least three characters.

Here's a quick fix (I didn't test it very thoroughly):
`'~\b(?<!://|">)www(?:\.[a-z0-9][-a-z0-9]*+)+\.[a-z]{2,6}+\b(?:[^<\s]*(?:/|\b))?~i'`

**Comment by AlexC** [comment]
Thanks, good catch. Looking further into the regex, I can't see why the ending of this regex is as it is (I didn't make the original, just amended for this bug). The following regex works just fine for me under many examples that I tried. Do you see any issues with this one?

```
~\b(?<!://|">)www(?:\.[a-z0-9][-a-z0-9]*+)+\.[a-z]{2,6}[^<\s]*~i
```

**Comment by GeertDD** [comment]
The ending is important for dealing with trailing punctuation. Your last suggestion matches the commas as part of the URL too. It's tricky stuff. The more tests the better.

```
Text::auto_link_urls('www.example.be,');
Text::auto_link_urls('www.example.be/');
Text::auto_link_urls('www.example.be/,');
```

**Comment by AlexC** [comment]
The original bug #4208 should now be fixed with the change I just made. I've also included some more unit tests for this function to ensure its behaviour.

The issue with trailing punctuation is another bug, mostly (only?) to do with trailing slashes now. Commas work as expected (they do not become part of the URL). I'll report this as another bug and see what I can do.

**Comment by zeelot** [comment]
@GeertDD are you fine with this now? Just trying to merge in any final fixes before the release :)

**Pull request merged**
