### PR TITLE
refs #4701: Prevent hash length extension attack.

### PR DESCRIPTION
**Pull request by birkir**
http://blog.whitehatsec.com/hash-length-extension-attacks/

### CODE REVIEW

**Comment by zeelot** [comment]
I think this would be fine in `3.3.1`, @zombor?

**Comment by rjd22** [comment]
If the behavior didn't change but is only made more secure so it should be fine. I see this more like a security patch.

**Comment by birkir** [comment]
Behavior does not change. Also allows other algorithm options (feature). <code>PHP 5 >= 5.1.2</code>

**Comment by marklocker** [comment]
Just stumbled upon this, has it not been merged in yet? Seems like it should be in `3.3.2` if not…

**Comment by zombor** [comment]
There's no behavior change, but there's an api-ish change here. I think existing cookies would break?

**Comment by rjd22** [comment]
@zombor Yea, could be true. That wouldn't be a bad thing since I expect cookies to need to be remade on a framework upgrade.

**Comment by zombor** [comment]
On a minor bugfix version update?

**Comment by rjd22** [comment]
@zombor Well I didn't say it's an easy call but this is a security patch. Making it secure it more important than having people reload their cookies IMO.

**Comment by zeelot** [comment]
I think we can merge this into minor versions. Cookies would be invalidated but it doesn't require anyone to change any code and it makes it more secure.

**Comment by WinterSilence** [comment]
It is not the same thing:

```
hash_hmac('sha1', $agent.$name.$value.Cookie::$salt, Cookie::$salt)
MAC = hash(key + hash(key + message))
```

Not only `PHP 5 >= 5.1.2`, `PECL hash >= 1.1` too.

'sha1' not soo "strong" algo, need use  'sha512', 'whirlpool', 'sha384', 'ripemd320' 

Its "gentle" version, but i think it need rewrite to "strong": if hash ext or algo not exists throw exception.

```
/**
* Use function [hash_hmac](http://php.net/hash-hmac) to generate salt.
* For more information, see [FAQ safe hashing](http://php.net/faq.passwords).
*
* @var  boolean
*/
public static $hash_hmac = FALSE;

/**
* Name of hashing algorithm, recommended values: 'sha512', 'whirlpool', 'sha384', 'ripemd320'.
* Use [hash-algos](http://php.net/hash-algos) to get available algorithms.
*
* @var  string
*/
public static $hash_hmac_algo = 'sha512';

/**
* @var  boolean  Flag "check hash": extension available and algorithm supporteded?
*/
protected static $_hash_hmac;

/**
* Generates a salt string for a cookie based on the name and value.
*
*     $salt = Cookie::salt('theme', 'red');
*
* @param   string  $name   Name of cookie
* @param   string  $value  Value of cookie
* @return  string
* @throws  Kohana_Exception
*/
public static function salt($name, $value)
{
    // Require a valid salt
    if ( ! Cookie::$salt)
    {
        throw new Kohana_Exception('A valid cookie salt is required. Please set Cookie::$salt.');
    }

    // Determine the user agent
    $agent = isset($_SERVER['HTTP_USER_AGENT']) ? strtolower($_SERVER['HTTP_USER_AGENT']) : 'unknown';

    if (Cookie::$hash_hmac)
    {
        if ( ! isset(Cookie::$_hash_hmac))
        {
            // Check hash_hmac only once
            Cookie::$_hash_hmac = (
                function_exists('hash_hmac') 
                AND in_array(Cookie::$hash_hmac_algo, hash_algos())
            );
        }

        if (Cookie::$_hash_hmac)
        {
            // Generate [HMAC](http://wikipedia.org/wiki/HMAC) salt 
            return hash_hmac(Cookie::$hash_hmac_algo, $agent.$name.$value, Cookie::$salt);
        }
        elseif (Kohana::$environment !== Kohana::PRODUCTION) 
        {
            // @todo This block to discuss: add or not?
            throw new Kohana_Exception(
                'Hash extension not available or algorithm :algo not supporteded.',
                array(':algo' => Cookie::$hash_hmac_algo)
            );
        }

        // Disable, if it unavailable
        Cookie::$hash_hmac = FALSE;
    }

    // Default generation of salt
    return sha1($agent.$name.$value.Cookie::$salt);
}
```

**Comment by WinterSilence** [comment]
"silence" version:

```
/**
* Use function [hash_hmac](http://php.net/hash-hmac) to generate salt.
* For more information, see [FAQ safe hashing](http://php.net/faq.passwords).
*
* @var  boolean|int
*/
public static $hash_hmac = FALSE;

/**
* Name of hashing algorithm, recommended values: 'sha512', 'whirlpool', 'sha384', 'ripemd320'.
* Use [hash-algos](http://php.net/hash-algos) to get available algorithms.
*
* @var  string
*/
public static $hash_hmac_algo = 'sha512';

/**
* Generates a salt string for a cookie based on the name and value.
*
*     $salt = Cookie::salt('theme', 'red');
*
* @param   string  $name   Name of cookie
* @param   string  $value  Value of cookie
* @return  string
* @throws  Kohana_Exception
*/
public static function salt($name, $value)
{
    // Require a valid salt
    if ( ! Cookie::$salt)
    {
        throw new Kohana_Exception('A valid cookie salt is required. Please set Cookie::$salt.');
    }

    // Determine the user agent
    $agent = isset($_SERVER['HTTP_USER_AGENT']) ? strtolower($_SERVER['HTTP_USER_AGENT']) : 'unknown';

    // If is integer, then we already check ext & algo
    if (Cookie::$hash_hmac === TRUE)
    {
        Cookie::$hash_hmac = (int)(
            function_exists('hash') 
            AND in_array(Cookie::$hash_hmac_algo, hash_algos())
        );
    }

    if (Cookie::$hash_hmac)
    {
        // Generate [HMAC](http://wikipedia.org/wiki/HMAC) salt 
        return hash_hmac(Cookie::$hash_hmac_algo, $agent.$name.$value, Cookie::$salt);
    }

    // Default generation of salt
    return sha1($agent.$name.$value.Cookie::$salt);
}
```

**Comment by WinterSilence** [comment]
"strong" version

```
/**
* Use function [hash_hmac](http://php.net/hash-hmac) to generate salt.
* For more information, see [FAQ safe hashing](http://php.net/faq.passwords).
*
* @var  boolean|int
*/
public static $hash_hmac = FALSE;

/**
* Name of hashing algorithm, recommended values: 'sha512', 'whirlpool', 'sha384', 'ripemd320'.
* Use [hash-algos](http://php.net/hash-algos) to get available algorithms.
*
* @var  string
*/
public static $hash_hmac_algo = 'sha512';

/**
* Generates a salt string for a cookie based on the name and value.
*
*     $salt = Cookie::salt('theme', 'red');
*
* @param   string  $name   Name of cookie
* @param   string  $value  Value of cookie
* @return  string
* @throws  Kohana_Exception
*/
public static function salt($name, $value)
{
    // Require a valid salt
    if ( ! Cookie::$salt)
    {
        throw new Kohana_Exception('A valid cookie salt is required. Please set Cookie::$salt.');
    }

    // Determine the user agent
    $agent = isset($_SERVER['HTTP_USER_AGENT']) ? strtolower($_SERVER['HTTP_USER_AGENT']) : 'unknown';

    if (Cookie::$hash_hmac)
    {
        if (Cookie::$hash_hmac === TRUE)
        {
            if ( ! function_exists('hash'))
            {
                throw new Kohana_Exception('Hash extension not available.');
            }
            elseif ( ! in_array(Cookie::$hash_hmac_algo, hash_algos()))
            {
                throw new Kohana_Exception(
                    'Hashing algorithm :algo not supporteded.',
                    array(':algo' => Cookie::$hash_hmac_algo)
                );
            };
            // Change type to check this block only once
            Cookie::$hash_hmac = 1;
        }

        // [HMAC](http://wikipedia.org/wiki/HMAC) salt generator
        return hash_hmac(Cookie::$hash_hmac_algo, $agent.$name.$value, Cookie::$salt);
    }

    // Default salt generator
    return sha1($agent.$name.$value.Cookie::$salt);
}
```

**Comment by enov** [comment]
@WinterSilence 

<br>

> It is not the same thing:
> 
> `hash_hmac('sha1', $agent.$name.$value.Cookie::$salt, Cookie::$salt)`
> `MAC = hash(key + hash(key + message))`

The article linked by @birkir states that:

> HMAC does something like this:
> `MAC = hash(key + hash(key + message))`

It does not say that you need to do that way. It's just that HMAC function does _something_ like that.

<br>

Regarding the availability of hash extension, from the [PHP manual](http://php.net/manual/en/hash.requirements.php)

> The Hash extension requires no external libraries and is enabled by default as of PHP 5.1.2

<br>

Regarding the choice of the algorithm,

> 'sha1' not soo "strong" algo, need use 'sha512', 'whirlpool', 'sha384', 'ripemd320'

Well there is [a research for a theoretical attack on SHA1 algorithm](https://code.google.com/p/hashclash/), but it seems to me that's an incomplete research.

**Comment by enov** [comment]
Excellent @birkir. Merged in #569.

**Pull request closed without merging**
