### PR TITLE
Clarify in "upgrading" guide that config now merges across sources

### PR DESCRIPTION
**Pull request by acoulton**
See ticket http://dev.kohanaframework.org/issues/4089

A possible new intro to the config section in the "upgrading to 3.2 guide" to highlight the new config merging behaviour.

### CODE REVIEW

**Comment by acoulton** [comment]
Hm, first time attempting the github "fork and pull" (away from my dev box) and it seems to have changed all the newlines.

In case it's easier to do it manually than trying to pull in this commit, the actual change I'm proposing is to update the very beginning to:

The configuration system has been rewritten to make it more flexible. The most significant change is that config 
groups are now merged across all readers, similar to how files cascade within the cascading filesystem. Therefore
you can now override a single config value (perhaps a database connection string, or a 'send-from' email address)
and store it in a separate config source (environment config file / database / custom) while inheriting the 
remaining settings from that group from your application's configuration files.

In other respects, the majority of the public API....

**Comment by kiall** [comment]
It looks like you somehow managed to muck up the commit, rather than the pull :)

You made a copy of this file "guide/kohana/upgrading.md" and called it "develop/guide/kohana/upgrading.md".. Hence its showing as an entirely new file..

**Comment by kiall** [comment]
Fixed+Merged here https://github.com/kohana/core/commit/f3979f80791022d39bf2d065d25ced12c2286b40

**Comment by acoulton** [comment]
Bizarre, I literally just browsed to the file on github, hit the fork and
edit button and followed through to make a pull from that.

My guess is that there might be an error in the fork and edit related to
using / in the branch name - I'll see if I can repeat and let the github
guys know if so - I've previously done it the old fashioned way and edited
locally, this is the first time I've tried doing it straight on gh.

Cheers
Andrew

On 11 Jul 2011 16:56, "kiall" <
reply@reply.github.com>
wrote:
Fixed+Merged here
https://github.com/kohana/core/commit/f3979f80791022d39bf2d065d25ced12c2286b40

##

**Pull request closed without merging**
