### PR TITLE
Refs #4375 - Parameter order for HTTP/Controller::redirect()

### PR DESCRIPTION
**Pull request by kemo**
Redmine issue: http://dev.kohanaframework.org/issues/4375

More info in this discussion: https://github.com/kohana/core/commit/7719279b609d056aeb92397ae206f56b491af3bd#classes/kohana/controller.php-P12

### CODE REVIEW

**Comment by kiall** [comment]
Heh - I had this cherry-picked and was writing tests for it ;) Was wondering why I couldn't push anymore!

**Comment by zombor** [comment]
This wasn't ready for merge. There were no test changes.

**Comment by kiall** [comment]
Its okay - I added the tests in another commit..

**Comment by shadowhand** [comment]
Jenkins said the build had passed, so I assumed it was safe...

**Pull request merged**
