### PR TITLE
Synapse bugfix/3447 and 3448

### PR DESCRIPTION
**Pull request by zeelot**
- http://dev.kohanaframework.org/issues/3448
- http://dev.kohanaframework.org/issues/3447

### CODE REVIEW

**Comment by shadowhand** [comment]
Is this pull request defunct?

**Comment by zeelot** [comment]
seems to be now

**Comment by shadowhand** [comment]
Closing, does not apply to 3.1 or 3.0 at this point.

**Comment by shadowhand** [comment]
Picked only the "merging wildcard" commit, as the other is invalid (see [3447 comments](http://dev.kohanaframework.org/issues/3447#note-4)). 2b1a1c30bf8266a6dc9dcb4283d95608ba37cc82

**Pull request closed without merging**
