### PR TITLE
HTTP::request_headers trim 'HTTP_' only at the beginning

### PR DESCRIPTION
**Pull request by enov**
A bug fix by @WinterSilence at #614, with failing tests.

Thanks.

### CODE REVIEW

**Comment by rjd22** [comment]
@enov is this a fix for the following?:

https://github.com/kohana/kohanaframework.org/issues/27

**Comment by rjd22** [comment]
@enov :+1:

**Comment by enov** [comment]
No, [that](https://github.com/kohana/kohanaframework.org/issues/27) was fixed [here](https://github.com/kohana/core/pull/608).

**Comment by enov** [comment]
Thanks for the review @rjd22.

**Comment by enov** [comment]
@acoulton if you have time for this, after which we need probably to do a release :rocket:

**Comment by acoulton** [comment]
@enov sure :)

**Comment by enov** [comment]
Thanks @acoulton. cc @WinterSilence.

@acoulton would you like to release it yourself?

**Pull request merged**
