### PR TITLE
Add IS.METHOD functions

### PR DESCRIPTION
**Pull request by nike-17**
Little fix that's fix annoying problem
-- all the time i need to check type of request 0method in controller i should make ugly check like 
$this->request->method() === 'POST'
it can be reason of some bugs e.g.

$this->request->method() === 'post'

is think 
$this->request->is_post() 
is more readable and more bug less way

### CODE REVIEW

**Comment by cs278** [comment]
Or just, `$this->request->method() === Request::GET`.

**Comment by zombor** [comment]
@cs278 has it right.

**Comment by antmat** [comment]
It is more comfortable to use is_\* method. Besides it is more safe.

**Comment by sergeyklay** [comment]
Yes, that's right.

it's comfortable:
`method() === Request::GET`
`method() === Request::POST`
`method() === Request::PUT`
`method() === Request::DELETE`

**Comment by nike-17** [comment]
Серега иди в жопу. Реально заябывает писать эту поебень.

**Comment by sergeyklay** [comment]
:D

**Comment by sergeyklay** [comment]
@nike-17 Кстати, кстати...

``` php
public function post_isset()
{
    if ( ! $this->post())
    {
        return FALSE;
    }

    $params = func_get_args();
    foreach ($params as $param)
    {
        if ($this->post($param) === NULL)
        {
            return FALSE;
        }
    }

    return TRUE;
}
```

Например

``` php
Request::current()->post_isset('post_var1', 'post_another_var', 'yet_another_var');
```

:)

**Pull request closed without merging**
