### PR TITLE
Update Core.php

### PR DESCRIPTION
**Pull request by dimonbat**
Hi!
is it good idea?
;)

### CODE REVIEW

**Comment by WinterSilence** [comment]
3.2 & 3.3 closed

**Comment by enov** [comment]
Thanks @dimonbat, but we can't directly merge to 3.3/master.

But this reminds me that we need to change those before releasing 3.3.3.
cc @acoulton

**Comment by acoulton** [comment]
@enov is there a "what to do for a release" document anywhere that you know of? Maybe we should make one?

**Comment by enov** [comment]
I am not aware of such document. @shadowhand definitely knows about this.

**Comment by lenton** [comment]
@acoulton @enov https://github.com/kohana/core/blob/3.4/develop/guide/kohana/upgrading.md

**Comment by enov** [comment]
@lenton "what are the steps to release a new Kohana version" :)

**Comment by enov** [comment]
It's basically
- Change the version (maybe also the codename)
- git merge to master
- git tag the version
- prepare a zip to be downloaded from the website
- prepare the guides for official modules in case of a new version (this seems tricky)
- etc...

@shadowhand?

**Comment by lenton** [comment]
Oh right, well the contributing doc mentions a little about a release branch: https://github.com/kohana/kohana/blob/3.4/develop/CONTRIBUTING.md#branch-name-meanings

**Comment by enov** [comment]
Hmm.. you're right:

> release branches are for maintenance work before a release. This branch should be branched from the develop branch only. Change the version number/code name here, and apply any other maintenance items needed before actually releasing. Merges from master should only come from this branch. It should be merged to develop when it's complete as well. This branch is deleted after it's done.

**Comment by shadowhand** [comment]
We basically use [git flow](http://nvie.com/posts/a-successful-git-branching-model/), slightly modified to include the various dev version branches.

**Comment by acoulton** [comment]
@shadowhand I was more meaning the non-git steps - changing version number in files, etc - @enov's [list](https://github.com/kohana/core/pull/479#issuecomment-63636915)  has most of what I can think of, anything else you know about?

**Pull request closed without merging**
