### PR TITLE
3.1.x

### PR DESCRIPTION
**Pull request by ellisio**
Fixes #3755 and #3759.

### CODE REVIEW

**Comment by shadowhand** [comment]
Needs a unit test. :(

**Comment by ellisio** [comment]
How do I unittest this? (I have yet to figure out how to setup Unit Test on my local computer...)

**Comment by shadowhand** [comment]
Beats me, but zombor will punch someone in the face if this is merged without one.

**Comment by ellisio** [comment]
I'll sacrific my face's beauty for the merge. :)

**Comment by ellisio** [comment]
I ran the ResponseTest unit test and received the following:

PHPUnit 3.5.13 by Sebastian Bergmann.

............

Time: 1 second, Memory: 13.00Mb

OK (12 tests, 23 assertions)

Do I need to actually make a test within that ResponseTest.php to get this merged in?

**Comment by ellisio** [comment]
Never mind, it looks like these fixes have already gone into the core with something else. Closing this PR.

**Pull request closed without merging**
