### PR TITLE
Update version in the dev branch

### PR DESCRIPTION
**Pull request by gnovaro**
const VERSION  = '3.4.1';
const CODENAME = 'uluru';  //new codename?

### CODE REVIEW

**Comment by acoulton** [comment]
@gnovaro shouldn't it be 3.4.0?

**Comment by enov** [comment]
As per the contributing guideline, this commit should be made on a separate `3.4/release` branch,  before merging to master.

**Comment by gnovaro** [comment]
Ok

El miércoles, 2 de septiembre de 2015, Samuel Demirdjian <
notifications@github.com> escribió:

> As per the contributing guideline, this commit should be made on a
> separate 3.4/release branch, before merging to master.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kohana/core/pull/634#issuecomment-137063526.

## 

_Gustavo A. Novaro_
Celular: +54 9 11 15-5757-7730
Seguime en Twitter: @gnovaro https://twitter.com/#%21/gnovaro

**Comment by neo22s** [comment]
we agreed on calling it 4.0.0. thanks!

**Pull request closed without merging**
