### PR TITLE
Add Windows 8 support

### PR DESCRIPTION
**Pull request by tbbuck**
Hi there,

This is just a quick change to add support for Windows 8 to the user agents config file.

This my first pull request, and if I've done something stupid, please forgive me, I'll learn :-)

Thanks,
Tom.

### CODE REVIEW

**Comment by shadowhand** [comment]
@kohana/owners this needs to be merged into 3.3.

**Comment by zeelot** [comment]
dude (@shadowhand), you can't merge pull requests into master -_- we have develop branches!

**Comment by shadowhand** [comment]
Oh shit, wasn't paying attention. Reverting...

**Comment by shadowhand** [comment]
7da9089767f3333d136c6ae214d7e43a4d822d0d and 3c7fc8c8afd127efcba9750ca8bc8565d7764baf

Merged up to 3.3/develop in cbf75f04ff0396077aae35c37c63ab19920280ec

**Pull request merged**
