### PR TITLE
#3141 - Handle indexed arrays consistently in Arr::merge()

### PR DESCRIPTION
**Pull request by cbandy**
The first commit adds more tests for existing behavior. The second commit changes behavior for indexed arrays, and appears faster, too.

### CODE REVIEW

**Comment by shadowhand** [comment]
This seems completely straight forward to me. +1

**Comment by cbandy** [comment]
@acoulton The issue you are describing is captured elsewhere: http://dev.kohanaframework.org/issues/4324

**Comment by acoulton** [comment]
@cbandy yes, I saw that these two are related - just wanted to note for clarity that although this fix will make the server arrays be merged as expected, it doesn't actually resolve #4324 which will still need those config arrays to be switched to associative. Some of the comment in #3141 isn't clear about this.

Definitely think this should be merged.

**Comment by cs278** [comment]
The type hint has been removed from the parameters?

**Pull request merged**
