### PR TITLE
Fixes #4112, fix __() to use default source language

### PR DESCRIPTION
**Pull request by ernestas**

### CODE REVIEW

**Comment by kiall** [comment]
Apologies for the spam, Just fixed a bug with the builder.

!build

**Comment by shadowhand** [comment]
This pull request does not do enough. In every case where Kohana is currently calling `__(...)`, it needs to explicitly state `__(..., 'en-us')` or messages are no longer going to translate properly.

**Comment by ernestas** [comment]
@shadowhand there are tickets for that. I'll change this pull to be against 3.3.

Tickets listed in first comment: http://dev.kohanaframework.org/issues/4145#note-1

**Comment by ernestas** [comment]
https://github.com/kohana/core/pull/195

**Pull request closed without merging**
