### PR TITLE
#4801 - update view guide

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by rjd22** [comment]
Please add the class and function close tags back in. This promotes good practice.

**Comment by WinterSilence** [comment]
where?

**Comment by rjd22** [comment]
These lines:
https://github.com/kohana/core/pull/433/files#diff-5c0a36c38f7ee053e336e507844b3665L92
https://github.com/kohana/core/pull/433/files#diff-5c0a36c38f7ee053e336e507844b3665L94
https://github.com/kohana/core/pull/433/files#diff-5c0a36c38f7ee053e336e507844b3665L105
https://github.com/kohana/core/pull/433/files#diff-5c0a36c38f7ee053e336e507844b3665L107

Just check the rendered version:
https://github.com/kohana/core/pull/433/files?short_path=5c0a36c#diff-5c0a36c38f7ee053e336e507844b3665

**Comment by WinterSilence** [comment]
Clarify the question of `~~~`?

**Pull request closed without merging**
