### PR TITLE
3.1/master

### PR DESCRIPTION
**Pull request by tonyhb**
Fixing http://dev.kohanaframework.org/issues/3857 (currently invalid, but I'm not sure I explained it well enough)

### CODE REVIEW

**Comment by kiall** [comment]
'min_length' cannot be included in $_empty_rules .. 

If it is, then optional fields that have a min length are impossible.

The addition of 'valid::not_empty' and 'valid::matches' to $_empty_rules is probably valid though, even though there not intended to be used that way..

**Comment by tonyhb** [comment]
Didn't think of that, sorry.

**Comment by kiall** [comment]
One other nitpick ;) Send pull requests to 3.1/develop rather than 3.1/master .. the master branches == the latest release .. so no changes go there directly..

**Comment by tonyhb** [comment]
Yezzir =)

Will take out the `min_length` and sort all of that out mate.

> ---
> 
>   kiall 
> mailto:reply@reply.github.com
> 16 March 2011 15:46
> 
> One other nitpick ;) Send pull requests to 3.1/develop rather than 
> 3.1/master .. the master branches == the latest release .. so no 
> changes go there directly..

**Pull request closed without merging**
