### PR TITLE
Fixes Issue #4615 #4022 and #4021

### PR DESCRIPTION
**Pull request by rjd22**
I've fixed the 3 issues in the Arr class. This fix won't work upstream since in Kohana 3.3 we start using arrayaccess. I need to checkout if these are really good for performance but I doubt it ;)

### CODE REVIEW

**Comment by kemo** [comment]
I don't think the isset() call should stay in there

**Comment by rjd22** [comment]
@kemo I think it should. The problem with array_key_exists is that it's 4 times slower than isset. Using both will get us the best of both worlds.

**Comment by rjd22** [comment]
@kemo look at the discussion here: https://github.com/kohana/core/pull/299

**Comment by kemo** [comment]
Speed over readability does make a point in this case, I agree. The `array_key_exists()` is a fail-over for NULL / undefined values anyways so... Ignore my previous comment

**Comment by zeelot** [comment]
can any of you guys explain this to me? https://bugs.php.net/bug.php?id=46354 it seems to say that since `5.3.0`, array_key_exists() does not work on any Object, but my test shows it does… so I'm confused but this would affect whether we can make this change or not (or in which version).

**Comment by rjd22** [comment]
Since after a lot of debate we came to the conclusion this should be fixed in 3.4 I'm closing this pull.

**Pull request closed without merging**
