### PR TITLE
Fix Valid::range bug excluding min/max values

### PR DESCRIPTION
**Pull request by dm**
Closes #4672 bug introduced in 23e1b0b

### CODE REVIEW

**Comment by Svish** [comment]
Yes please!

**Comment by zeelot** [comment]
Could you link to this PR from the ticket? Thanks :)

**Comment by evanpurkhiser** [comment]
:+1: on this. Just ran into this a few days ago.

**Comment by dm** [comment]
@Zeelot already did, right after opening it [4672](http://dev.kohanaframework.org/issues/4672) :)

Jeremy Bush last touched the issue a month ago, I assumed, to get it on the 3.3.1 list. (Plus some confusion over which pull request to accept...)

**Comment by zeelot** [comment]
thanks

**Pull request merged**
