### PR TITLE
Set the content-length in case request body be changed after $request->render().

### PR DESCRIPTION
**Pull request by sunchuo**
$request = Request::factory('http://www.google.com/')->method(Request::POST)->post(['aaa' => 'bbb']);
echo $request; // request->render() set the content-length as 0.
$response = $request->execute(); //request error

### CODE REVIEW

**Comment by enov** [comment]
Hey @sunchuo,

I tried the code you posted. I do not receive any request errors.

Also, an `echo $request;` after `$request->execute()` shows correct content length:

```
POST http://www.google.com/ HTTP/1.1 Content-Type: application/x-www-form-urlencoded; charset=utf-8 Content-Length: 7 aaa=bbb
```

**Comment by sunchuo** [comment]
$request = Request::factory('http://www.google.com/')->method(Request::POST)->post(['aaa' => 'bbb']);
echo $request;

this will set the content-length = 0

···
POST http://www.google.com/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Content-Length: 0
···

then call $request->execute() after echo $request , the content-length header still  0.

···
POST http://www.google.com/ HTTP/1.1
Host: www.google.com
Accept: _/_
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Content-Length: 0
···

the server will receive a empty post request because the content-length 0.

$request->render() will set the content-length so we must reset it before $request->execute().

sorry for my poor English.😢

**Comment by enov** [comment]
@sunchuo confirmed. I was able to duplicate the issue:

``` php
$request = Request::factory('https://httpbin.org/post')->method(Request::POST)->post(['aaa' => 'bbb']);
$request->render();
echo $request->execute();
```

Results:

``` json
{ "args": {}, "data": "", "files": {}, "form": {}, "headers": { "Accept": "*/*", "Content-Length": "0", "Content-Type": "application/x-www-form-urlencoded; charset=utf-8", "Host": "httpbin.org" }, "json": null, "origin": "89.249.216.117", "url": "https://httpbin.org/post" }
```

Without calling `$request->render()`:

``` json
{ "args": {}, "data": "", "files": {}, "form": { "aaa": "bbb" }, "headers": { "Accept": "*/*", "Content-Length": "7", "Content-Type": "application/x-www-form-urlencoded; charset=utf-8", "Host": "httpbin.org" }, "json": null, "origin": "89.249.216.117", "url": "https://httpbin.org/post" }
```

**Comment by enov** [comment]
I think a better solution would be to get the following lines from `Request_Client_External`:

https://github.com/kohana/core/blob/3.3/master/classes/Kohana/Request/Client/External.php#L123-L128

``` php
// Resolve the POST fields
if ($post = $request->post())
{
    $request->body(http_build_query($post, NULL, '&'))
            ->headers('content-type', 'application/x-www-form-urlencoded; charset='.Kohana::$charset);
}
```

and reuse them in `Request::render()`, instead of the following lines:

https://github.com/kohana/core/blob/3.3/master/classes/Kohana/Request.php#L1227-L1236

``` php
if ( ! $post = $this->post())
{
    $body = $this->body();
}
else
{
    $this->headers('content-type',
        'application/x-www-form-urlencoded; charset='.Kohana::$charset);
    $body = http_build_query($post, NULL, '&');
}
```

This way, `content-length` header is well calculated on the [next line](https://github.com/kohana/core/blob/3.3/master/classes/Kohana/Request.php#L1239). (`Request::content_length()` [calculates the length from the body](https://github.com/kohana/core/blob/3.3/master/classes/Kohana/Request.php#L1208-L1211)).

**Comment by enov** [comment]
@sunchuo I noticed that you already fixed it. Thanks.

I can not merge directly to `3.3/master`. Could you redo this in a single commit and PR to `3.3/develop`? Thank you for your patience.

@acoulton @rjd22 kindly review. Thanks.

**Comment by sunchuo** [comment]
@enov here is the new pull request #655

**Pull request closed without merging**
