### PR TITLE
Error, delete method called by get method

### PR DESCRIPTION
**Pull request by zogame**
ErrorException [ 2 ]: Cookie names cannot contain any of the following '=,; \t\r\n\013\014' ~ SYSPATH/classes/Kohana/Cookie.php

### CODE REVIEW

**Comment by enov** [comment]
Hey @Zogame,

Thanks for this. Could you give us a code to reproduce this? Perhaps you are using invalid characters while getting a cookie? Maybe [this](https://github.com/slimphp/Slim/issues/115) is related? Silencing an exception might not be the right way to solve things. Kindly dig deeper and provide us with better insight/patch.

I will leave this open for the time being. Thanks.

**Comment by zogame** [comment]
Hi @enov ,

A reproduction cord is this.

``` PHP
Cookie::set("foo=,; \t\r\n", 'value');
```

but, I write a right code again.　Thanks.

**Comment by enov** [comment]
@Zogame I see that an exception is legitimate in that case. [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1) states that cookie name should be tokens as described in [RFC 2616](https://tools.ietf.org/html/rfc2616#section-2.2):

> ```
>    token          = 1*<any CHAR except CTLs or separators>
>    separators     = "(" | ")" | "<" | ">" | "@"
>                   | "," | ";" | ":" | "\" | <">
>                   | "/" | "[" | "]" | "?" | "="
>                   | "{" | "}" | SP | HT
> ```

`CTL` stands for any US-ASCII control character (octets 0 - 31) and DEL (127).

If you really need to set Cookies with exceptional names, I suggest you base64 encode/decode them at the application level.

**Comment by zogame** [comment]
I get it.
The exception is correct.
Close this. Thanks.

**Pull request closed without merging**
