### PR TITLE
Fix extraneous white space in Validation.php

### PR DESCRIPTION
**Pull request by evanpurkhiser**
I know pull requests are usually supposed to have issue references in redmine, but this was such a minor change I figured hopefully it would be ok =)

### CODE REVIEW

**Comment by sergeyklay** [comment]
I've seen a lot of similar things. Why don't fix all then?

**Comment by evanpurkhiser** [comment]
Every little bit helps right?

**Comment by sergeyklay** [comment]
right :smile_cat:

**Comment by zeelot** [comment]
thanks :)

**Pull request merged**
