### PR TITLE
doc: use "303 See Other" redirects after POST

### PR DESCRIPTION
**Pull request by ktdreyer**
Per RFC 2616 (HTTP 1.1), the HTTP response status code "303 See Other" is the correct way to redirect a client after an HTTP POST. Adjust the documentation to use a 303 redirect instead of 302.

### CODE REVIEW

**Comment by ktdreyer** [comment]
Redmine ticket filed at http://dev.kohanaframework.org/issues/4720

**Comment by zombor** [comment]
There was a reason we chose 302 vs 303 even though 303 is "correct". I'm not sure offhand, maybe it was browser support?

**Comment by ktdreyer** [comment]
Closing for #343, which is filed against the proper branch (3.3/develop)

**Comment by sergeyklay** [comment]
:+1:

**Pull request closed without merging**
