### PR TITLE
Added default uri values and automatic retaining of uri values to Kohana_Route

### PR DESCRIPTION
**Pull request by ymtn**
A route can be declared like this, with an optional key of, for instance, 'language'. This key will be automatically injected into all subsequent calls to Route::uri

```
Route::set('default', '(/<language>)(/<controller>(/<action>(/<id>)))',
    array(
        'language' => '(nl|en|fr)'
    ))
    ->defaults(array(
        'controller' => 'foo',
        'action'     => 'bar'
    ))
    ->retain(array(
        'language'
    ));
```

When on the location www.mysite.com/fr, a call to

```
Route::get('default')->uri(array('controller' => 'foo','action' => 'bar'))
```

Will render /fr/foo/bar

The function Route::uri_defaults can be used to set these default uri values explicitly:

```
Route::get('default')->uri_defaults(array('language'=>'fr'));
```

Changes to Kohana_Route:

Added
Kohana_Route::_retain
Kohana_Route::retain()
Kohana_Route::_uri_defaults
Kohana_Route::uri_defaults()

Changed
Kohana_Route::uri()
Kohana_Route::matches()

### CODE REVIEW

**Comment by samsoir** [comment]
This would be an api change, so it cannot go into 3.1 - possibility for it to go into 3.2 if it has a feature request ticket associated with it.

**Comment by ymtn** [comment]
I allready created an issue at http://dev.kohanaframework.org. for 3.1.3. 
Should I make another one for 3.2 ?

**Comment by samsoir** [comment]
Just update the existing ticket for 3.1.3 to target 3.2 instead. It will not go into 3.1.3 as it is an API change, so this is being rejected.

**Comment by ymtn** [comment]
Ok, 3.2 it is. 
It seems I can't update the ticket though; I can just add a comment.

**Comment by BRMatt** [comment]
Just for reference, ticket is [3943](http://dev.kohanaframework.org/issues/3943)

**Pull request closed without merging**
