### PR TITLE
PHP 7 support for exception handling

### PR DESCRIPTION
**Pull request by enov**
Related to #642. Thanks @neo22s.

### CODE REVIEW

**Comment by neo22s** [comment]
Cool! glad will be in 3.4.

Where is the best place to discuss about the future of 3.4? ;)

**Comment by enov** [comment]
@neo22s just open an issue and discuss. Preferably in kohana/kohana or kohana/core repos.

**Comment by neo22s** [comment]
@enov done, thanks! https://github.com/kohana/core/issues/660

**Comment by enov** [comment]
Thanks @acoulton, @neo22s.

**Pull request merged**
