### PR TITLE
3.0.x

### PR DESCRIPTION
**Pull request by ellisio**
Modified documentation for core to better support IDEs with support for auto-complete. Also altered some files that were doing assignments in conditions to be something like if(($var = something) != FALSE){}; basically just to make IDEs not bitch and moan.

### CODE REVIEW

**Comment by zombor** [comment]
Make sure you attach this to the proper issue on redmine so it's properly tracked.

**Comment by ellisio** [comment]
Pardon my ignorance, but how do I do that?

**Comment by zombor** [comment]
Link to this pull request here: http://dev.kohanaframework.org/issues/2893

Also, this won't be merged in, there's more than just phpdoc refactoring.

I'm going to close this, please send another one when there's only phpdoc changes.

**Comment by ellisio** [comment]
Roger that, will send another request shortly once I've rolled out the non-phpdoc changes.

**Pull request closed without merging**
