### PR TITLE
Merge branch '3.3/develop' into '3.4/develop'

### PR DESCRIPTION
**Pull request by enov**
Conflicts:
    classes/Kohana/Core.php
    classes/Kohana/Encrypt.php
    classes/Kohana/View.php
    tests/kohana/request/client/InternalTest.php

### CODE REVIEW

**Comment by acoulton** [comment]
@enov thanks, looks good to me. Are you happy for it to be merged?

**Comment by enov** [comment]
> Are you happy for it to be merged?

Hey @acoulton. You mean if it is ready for merge? Yeah...
Otherwise not sure what do you mean by _happy_ :smile:

**Comment by acoulton** [comment]
@enov yeah I meant ready. Hope you're happy too though :)

Thanks.

**Comment by enov** [comment]
Haha! Happy I am. Thanks @acoulton.

**Pull request merged**
