### PR TITLE
Fixes #4434 - Request::$initial and Request::$current changed to protected properties.

### PR DESCRIPTION
**Pull request by ghost**
#4434 - Request::$initial and Request::$current should be protected properties and only accessed via their corresponding methods Request::initial() and Request::current().

### CODE REVIEW

**Comment by kemo** [comment]
This doesn't follow Kohanas conventions

**Comment by radsystems** [comment]
In what way?

**Comment by kemo** [comment]
Protected properties must begin with an underscore

**Comment by radsystems** [comment]
I've closed this pull request as it is not a sufficient fix, since Request::$initial and Request::$current is used throughout the system core. Therefore renaming them or changing their scope will require more refactoring than was provided here. This is probably best left for a core developer to address if they decide it is a valid issue.

**Pull request merged**
