### PR TITLE
Issue #'s 4377, 4375, 4374, 4373

### PR DESCRIPTION
**Pull request by kiall**
Issue #'s 4377, 4375, 4374, 4373

### CODE REVIEW

**Comment by kiall** [comment]
Aplogies for such a large set of changes, but they all (mostly) ended up related/necessary for each other.

**Comment by shadowhand** [comment]
@kiall For future reference, rather than doing `git merge 3.3/develop` inside feature branches, do a `git rebase 3.3/develop` instead. This keeps the branches (and pull requests) cleaner.

**Comment by kiall** [comment]
Sorry shadowhand another merge, probably too late to use rebase on this one..

**Comment by shadowhand** [comment]
Once you merge, you can't go back. The only way to clean it up at this point is to create a new branch and cherry-pick the commits across.

**Comment by kiall** [comment]
Yea, Thats what I thought :)

On Tue, Jan 10, 2012 at 3:56 PM, Woody Gilk <
reply@reply.github.com

**Comment by kiall** [comment]
This test failure is a chicken and egg issue.. The pull request tester can't handle changes that span multiple repositories..

**Pull request merged**
