### PR TITLE
3.0.x

### PR DESCRIPTION
**Pull request by LegendSzymon-P**
redirect without index.php/

### CODE REVIEW

**Comment by shadowhand** [comment]
Mm, why?

**Comment by szymon-przybyl** [comment]
hm, becouse for example www.service.com/home/contact looks better than www.service.com/index.php/home/contact

**Comment by shadowhand** [comment]
Yes, but that is a configuration issue. If you set `index_file` to `FALSE` in bootstrap, then "index.php" will not be in the URL.

**Comment by szymon-przybyl** [comment]
oh, i didn't know, i was trying to set there '', but it doesn't worked, thanks :)

**Pull request closed without merging**
