### PR TITLE
Update Text.php

### PR DESCRIPTION
**Pull request by zogame**
$agent has been already defined

### CODE REVIEW

**Comment by enov** [comment]
Hmm, @Zogame , I think you have a good catch here.

Also, the doc above the method is confusing, could you review that too please?

**Comment by enov** [comment]
Also, now that I am reviewing `Kohana_TextTest`, it seems there are no tests covering `Text::user_agent`.

**Comment by enov** [comment]
BTW, you are targeting the wrong branch. This should target `3.3/develop`.

**Comment by zogame** [comment]
oh...Okay.

**Comment by enov** [comment]
Alright, I'll close this now. Please re-target to the correct branch. Thanks!

**Comment by enov** [comment]
@Zogame could you please re-target this to `3.3/develop`?

**Comment by zogame** [comment]
Is this correct?　3.3/develop new pull-request.

**Comment by enov** [comment]
Yeah, I guess so, just checking it now...

**Pull request closed without merging**
