### PR TITLE
Duplicate function call

### PR DESCRIPTION
**Pull request by misa**

### CODE REVIEW

**Comment by shadowhand** [comment]
It looks like this commit is no longer a valid patch against branch 3.0.x, please update and submit a new pull request.

**Comment by misa** [comment]
It was against master ...

**Comment by misa** [comment]
I am quite puzzled how to do it here

**Comment by shadowhand** [comment]
All patches need to be made against the 3.0.x branch, that is where development is done.

**Comment by shadowhand** [comment]
You need to checkout the 3.0.x branch, then create a new branch for your patch. Find the commit hash of your original commit, then do `git cherry-pick HASH` from within your patching branch. Then push your new branch and submit a pull request. Then you should only have a single commit attached.

**Pull request closed without merging**
