### PR TITLE
Fixes #3931: allows Kohana to shutdown properly and exit(1) in case of an exception

### PR DESCRIPTION
**Pull request by enov**

### CODE REVIEW

**Comment by zeelot** [comment]
You can't add class properties or methods in minor releases :(

**Comment by shadowhand** [comment]
Honestly... I know that `$GLOBALS` is evil, but this is probably a perfect use case for it.

**Comment by enov** [comment]
@Zeelot , @shadowhand ,

Here's another PR, that does not change Kohana's API in a minor release.

https://github.com/kohana/core/pull/460

However, this hack is extremely complicated, dirty and ugly.

**Comment by enov** [comment]
This is my third take on this subject, but this time very clean and readable!

https://github.com/kohana/core/pull/461

**Comment by zeelot** [comment]
Left you a comment there :)

**Pull request closed without merging**
