### PR TITLE
Patch for Issue #3226

### PR DESCRIPTION
**Pull request by joelpittet**
Ok I hope this makes life easier for you, it's fresh commit on the correct newly created 3.0.x forked branch.

### CODE REVIEW

**Comment by shadowhand** [comment]
Too many unrelated commits.

**Comment by shadowhand** [comment]
Please resubmit a pull request with only commits related to [3226](http://dev.kohanaframework.org/issues/3226).

**Comment by shadowhand** [comment]
Cherry picked the relavant commits, this is now fixed.

**Comment by joelpittet** [comment]
Maybe to make it easier I will create a new branch for each patch so that previous patches don't get pull requested along with the request?  Or is cherry picking an ok workflow?

**Comment by shadowhand** [comment]
Separate branches would help, yes.

**Pull request closed without merging**
